name: CI

on:
  pull_request:
    types: [opened, reopened]

jobs:
  cicd_test:
    name: CICD_TEST

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if PR is from develop to main branch
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" != "main" ] && [ "${{ github.event.pull_request.head.ref }}" = "develop" ]; then
            echo "Pull request not from develop to main branch, exiting with code 1"
            exit 1
          else
            echo "Pull request from develop to main branch, continuing..."
          fi
